version: '2'
services:
    backend-service:
        container_name: backend-service
        build: ./server
        command: nodemon
        volumes:
            - "./server:/app_src"
        ports:
            - "3000:3000"
